name: civix_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  dio: ^5.7.0
  dots_indicator: ^3.0.0
  email_validator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_pw_validator: ^1.6.0
  flutter_svg_provider: ^1.0.7
  gal: ^2.3.1
  geolocator: ^13.0.2
  get_it: ^8.0.2
  google_maps_flutter: ^2.10.1
  google_nav_bar: ^5.0.7
  image_picker: ^1.1.2
  jwt_decoder: ^2.0.1
  lottie: ^3.2.0
  modal_progress_hud_nsn: ^0.5.1
  permission_handler: ^11.3.1
  pinput: ^5.0.0
  shared_preferences: ^2.3.3
  skeletonizer: ^1.4.3
  smooth_page_indicator: ^1.2.0+3
  svg_flutter: ^0.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.jpg"
  adaptive_icon_background: "#192531"
  adaptive_icon_foreground: "assets/icon/forground.png"
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
  fonts:
    - family: ins
      fonts:
        - asset: assets/fonts/InstrumentSans-Regular.ttf
        - asset: assets/fonts/InstrumentSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/InstrumentSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/InstrumentSans-SemiBold.ttf
          weight: 600
    - family: inter
      fonts:
        - asset: assets/fonts/Inter_24pt-Regular.ttf
        - asset: assets/fonts/Inter_24pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_24pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_24pt-SemiBold.ttf
          weight: 600
flutter_assets:
  assets_path: assets/
  output_path: lib/core/utils/
  filename: app_images.dart
  field_prefix: null
flutter_intl:
  enabled: true
